#!/bin/bash

python3 /usr/lib/raspiwifi/reset_device/reset.py &

# The line below is added by me.
python3 /usr/lib/raspiwifi/configuration_app/app.py &

python3 /usr/lib/raspiwifi/reset_device/connection_monitor.py &
